export const SET_FULL_PAGE_AD_DATA = "SET_FULL_PAGE_AD_DATA";
export const SET_CONVERSATION_ID = "SET_CONVERSATION_ID";
export const SET_IS_CHAT_READY = "SET_IS_CHAT_READY";
export const SET_LIVEPERSON_ENGAGEMENT_DATA = "SET_LIVEPERSON_ENGAGEMENT_DATA";
export const SET_LIVEPERSON_CHAT_BUTTON_REF = "SET_LIVEPERSON_CHAT_BUTTON_REF";
export const SET_LIVEPERSON_TEXT_BUTTON_REF = "SET_LIVEPERSON_TEXT_BUTTON_REF";
